### ISSUE TITLE
Different values in known_third_party if there's a folder/file with the same name

### ISSUE THREAD

**Issue by paveldedik** [asottile/seed-isort-config#70] opened 2020-07-13 10:14 UTC
Hi, I think this issue is similar to this - https://github.com/asottile/seed-isort-config/issues/7

Basically the problem happens if we have a package in Python, e.g. `flask_session` which automatically also creates `flask_session` directory in the root of the git repository (used as a cache folder, note that this directory is in `.gitignore`). Than `seed-isort-config` cli produces different result than `pre-commit run -a`.

This is a problem, which I believe should be solved somehow. We also use `alembic` which creates `alembic` folder for migrations by default. If we run `pre-commit run -a` it will not add `alembic` to `known_third_party` because it uses the same nae as the Python package itself. Se our only option is to rename `alembic` folder to `migrations` or something like that.

This conflict in package name vs directory/filename is not good at all. And it also took some time to figure out why this is happening, so I believe it should be resolved somehow.

I'm using the latest version of seed-isort-config (v2.2.0), python 3.8 (I believe this is issue in all versions).

**Comment by asottile** [comment] 2020-07-13 14:15
A folder is a namespace module, I'd suggest fixing whatever tool is writing module-compatible names to your working directory:

```console
$ mkdir alembic
$ python3 -c 'import alembic; print(alembic)'
<module 'alembic' (namespace)>
```

since there's nothing that can be done here (beyond using `src` layout and setting `--application-directories`) and it is working as intended I'm closing this -- thanks for the issue nonetheless!

**Closed by asottile** 2020-07-13 14:15 UTC
