### ISSUE TITLE
observing unexpected regular changes for some users

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [asottile/seed-isort-config#22] opened 2018-10-30 18:36 UTC
hi, i'm reporting this issue on behalf of a coworker after doing some initial investigation

the git repo in question is https://github.com/ManageIQ/integration_tests

the user even after reinstalling pre-commit faced the following detail issues

```diff
diff --git a/.isort.cfg b/.isort.cfg
index f00acd605..be837f5e0 100644
--- a/.isort.cfg
+++ b/.isort.cfg
@@ -1,4 +1,4 @@
 [settings]
 line_length=100
 # NOTE: never change known_third_party by hand its managed by a hook
-known_third_party = Crypto,IPython,OpenSSL,PIL,_pytest,attr,bottle,bugzilla,cStringIO,cached_property,click,coverage,cycler,dateparser,dateutil,debtcollector,deepdiff,diaper,docker,dockerbot,dump2polarion,fauxfactory,freeze,gevent,git,github,glanceclient,humanfriendly,importscan,iso8601,jenkins,jinja2,jira,jsmin,keystoneauth1,kwargify,lxml,lya,manageiq_client,matplotlib,miq_version,navmazing,novaclient,numpy,paramiko,pathlib2,pdfminer,pika,pkg_resources,py,pygal,pytesseract,pytest,pytz,requests,riggerlib,rope,scp,selenium,sentaku,setuptools,six,slumber,sphinx,sphinx_rtd_theme,sqlalchemy,tabulate,tzlocal,urllib2,wait_for,werkzeug,widgetastic,widgetastic_patternfly,wrapanapi,xmltodict,yaml,yaycl,yaycl_crypt,zmq
+known_third_party = Crypto,IPython,OpenSSL,PIL,_pytest,attr,bottle,bugzilla,cached_property,click,concurrent,coverage,cycler,dateparser,dateutil,debtcollector,deepdiff,diaper,docker,dockerbot,dump2polarion,fauxfactory,freeze,gevent,git,github,glanceclient,humanfriendly,importscan,iso8601,jenkins,jinja2,jira,jsmin,keystoneauth1,kwargify,lxml,lya,manageiq_client,matplotlib,miq_version,navmazing,novaclient,numpy,paramiko,pathlib,pathlib2,pdfminer,pika,pkg_resources,py,pygal,pytesseract,pytest,pytz,requests,riggerlib,rope,scp,selenium,sentaku,setuptools,six,slumber,sphinx,sphinx_rtd_theme,sqlalchemy,tabulate,tzlocal,wait_for,werkzeug,widgetastic,widgetastic_patternfly,wrapanapi,xmltodict,yaml,yaycl,yaycl_crypt,zmq
```

the particular exchange in packages leads me to believe that pre-commit isn't quite sure which python version to use - and the seed tool adds certain packages based solely on whether its invoked on python3 or python2

**Comment by asottile** [comment] 2018-10-30 19:36
this is intentional (and partially addressed with the latest version https://github.com/asottile/seed-isort-config/pull/19).  it is suggested to use `language_version: ...` (if you're using pre-commit) to select the version you want to classify imports for.  `pre-commit` by default will use whatever interpreter version you're running as unless you specify otherwise

**Comment by asottile** [comment] 2018-10-30 19:38
the core of it is [`classify_import`](https://github.com/asottile/aspy.refactor_imports#aspyrefactor_importsclassify) uses the current running interpreter to determine whether something is "standard library"

**Comment by asottile** [comment] 2018-10-30 19:39
I notice that `ManageIQ/integration_tests` is using 1.2.0 -- maybe try under 1.3.0 -- should be more consistent there :+1:

**Comment by asottile** [comment] 2018-10-30 20:29
oops, closing this as it's working as intended.  -- try out 1.3.0 and `language_version: python3`!

**Closed by asottile** 2018-10-30 20:29 UTC
